<?php

namespace App\Entity;

use App\Repository\ConstructionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

/**
 * Represents a Construction project resource in the system.
 *
 * This entity stores information about construction projects including their
 * name, location, current stage, category, start date, and additional details.
 *
 * This entity is exposed as an API Platform resource with the following endpoints:
 * - GET /api/constructions - Retrieve collection of constructions
 * - GET /api/constructions/{id} - Retrieve a single construction
 * - POST /api/constructions - Create a new construction
 * - PUT /api/constructions/{id} - Replace an existing construction
 * - PATCH /api/constructions/{id} - Update an existing construction
 * - DELETE /api/constructions/{id} - Delete a construction
 *
 * @see https://api-platform.com/docs/core/operations/
 */
#[ORM\Entity(repositoryClass: ConstructionRepository::class)]
#[ORM\Table(name: 'constructions')]
#[ApiResource]
class Construction
{
    /**
     * @var int|null The unique identifier of the construction project.
     *               Auto-generated by the database.
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var string|null The name of the construction project.
     *                  Constraints: Maximum length of 200 characters.
     */
    #[ORM\Column(length: 200)]
    private ?string $name = null;

    /**
     * @var string|null The physical location or address of the construction project.
     *                  Constraints: Maximum length of 500 characters.
     */
    #[ORM\Column(length: 500)]
    private ?string $location = null;

    /**
     * @var int|null The current stage or phase of the construction project.
     *               Represented as a small integer value.
     *               Constraints: SMALLINT type.
     */
    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $stage = null;

    /**
     * @var string|null The category or type of construction project.
     *                  Constraints: Maximum length of 100 characters.
     */
    #[ORM\Column(length: 100)]
    private ?string $category = null;

    /**
     * @var \DateTimeInterface|null The start date of the construction project.
     *                              Stored as a mutable datetime value.
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    /**
     * @var string|null Detailed description or additional information about the construction project.
     *                  Stored as TEXT type for longer content.
     */
    #[ORM\Column(type: Types::TEXT)]
    private ?string $details = null;

    /**
     * @var int|null The ID of the user who created this construction project.
     *               References the creator/owner of the record.
     */
    #[ORM\Column]
    private ?int $creatorId = null;

    /**
     * Gets the unique identifier of the construction project.
     *
     * @return int|null The construction ID, or null if not yet persisted.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Gets the name of the construction project.
     *
     * @return string|null The construction project name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets the name of the construction project.
     *
     * @param string $name The construction project name.
     * @return static Returns self for method chaining.
     */
    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets the location of the construction project.
     *
     * @return string|null The physical location or address.
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets the location of the construction project.
     *
     * @param string $location The physical location or address.
     * @return static Returns self for method chaining.
     */
    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Gets the current stage of the construction project.
     *
     * @return int|null The stage number.
     */
    public function getStage(): ?int
    {
        return $this->stage;
    }

    /**
     * Sets the current stage of the construction project.
     *
     * @param int $stage The stage number.
     * @return static Returns self for method chaining.
     */
    public function setStage(int $stage): static
    {
        $this->stage = $stage;

        return $this;
    }

    /**
     * Gets the category of the construction project.
     *
     * @return string|null The project category.
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets the category of the construction project.
     *
     * @param string $category The project category.
     * @return static Returns self for method chaining.
     */
    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Gets the start date of the construction project.
     *
     * @return \DateTimeInterface|null The project start date.
     */
    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    /**
     * Sets the start date of the construction project.
     *
     * @param \DateTimeInterface $startDate The project start date.
     * @return static Returns self for method chaining.
     */
    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Gets the detailed description of the construction project.
     *
     * @return string|null The project details.
     */
    public function getDetails(): ?string
    {
        return $this->details;
    }

    /**
     * Sets the detailed description of the construction project.
     *
     * @param string $details The project details.
     * @return static Returns self for method chaining.
     */
    public function setDetails(string $details): static
    {
        $this->details = $details;

        return $this;
    }

    /**
     * Gets the ID of the user who created this construction project.
     *
     * @return int|null The creator's user ID.
     */
    public function getCreatorId(): ?int
    {
        return $this->creatorId;
    }

    /**
     * Sets the ID of the user who created this construction project.
     *
     * @param int $creatorId The creator's user ID.
     * @return static Returns self for method chaining.
     */
    public function setCreatorId(int $creatorId): static
    {
        $this->creatorId = $creatorId;

        return $this;
    }
}
